# Generated by Django 6.0.3 on 2026-03-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoMaquillaje',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No Disponible')], default='disponible', max_length=20)),
                ('fecha_ingreso', models.DateField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('marca', models.CharField(default='Sin marca', max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
            ],
            options={
                'verbose_name': 'Producto de Maquillaje',
                'verbose_name_plural': 'Productos de Maquillaje',
            },
        ),
    ]
