# Generated by Django 4.2 on 2026-06-17 15:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id_bodega', models.BigAutoField(db_column='id_bodega', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('ciudad', models.CharField(blank=True, max_length=80, null=True)),
                ('codigo_pais', models.CharField(default='CO', max_length=2)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bodega',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductoMaquillaje',
            fields=[
                ('id_inventario', models.BigAutoField(db_column='id_inventario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=160)),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(default='disponible', max_length=40)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marca', models.CharField(blank=True, max_length=120, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'producto_inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoMovimientoInventario',
            fields=[
                ('id_tipo_movimiento', models.PositiveSmallIntegerField(db_column='id_tipo_movimiento', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=160)),
                ('direccion', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'tipo_movimiento_inventario',
                'ordering': ['id_tipo_movimiento'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SaldoInventario',
            fields=[
                ('variante', models.OneToOneField(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='saldo_inventario', serialize=False, to='productos.varianteproducto')),
                ('cantidad_existencia', models.PositiveIntegerField(default=0)),
                ('cantidad_reservada', models.PositiveIntegerField(default=0)),
                ('nivel_reorden', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.CASCADE, related_name='saldos', to='inventario.bodega')),
            ],
            options={
                'db_table': 'saldo_inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.BigAutoField(db_column='id_movimiento', primary_key=True, serialize=False)),
                ('tipo_referencia', models.CharField(blank=True, max_length=40, null=True)),
                ('id_referencia', models.CharField(blank=True, max_length=80, null=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('bodega', models.ForeignKey(db_column='id_bodega', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='inventario.bodega')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
                ('tipo_movimiento', models.ForeignKey(db_column='id_tipo_movimiento', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='inventario.tipomovimientoinventario')),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemMovimientoInventario',
            fields=[
                ('id_item_movimiento', models.BigAutoField(db_column='id_item_movimiento', primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('movimiento', models.ForeignKey(db_column='id_movimiento', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.movimientoinventario')),
                ('variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos', to='productos.varianteproducto')),
            ],
            options={
                'db_table': 'item_movimiento_inventario',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='saldoinventario',
            index=models.Index(fields=['bodega', 'actualizado_en'], name='saldo_inven_id_bode_e5f25a_idx'),
        ),
    ]
