# Generated by Django 6.0.3 on 2026-03-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
    ]
