# Generated by Django 4.2 on 2026-06-19 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productomaquillaje',
            name='color',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='productomaquillaje',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
