# Generated by Django 4.2 on 2026-06-25 01:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_productomaquillaje_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomaquillaje',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='default.png', max_length=255, verbose_name='imagen'),
            preserve_default=False,
        ),
    ]
