# Generated by Django 4.2 on 2026-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_maquillaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productomaquillaje',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='productomaquillaje',
            name='nombre',
            field=models.CharField(db_index=True, max_length=160),
        ),
        migrations.AddIndex(
            model_name='saldoinventario',
            index=models.Index(fields=['bodega', 'actualizado_en'], name='saldo_inven_id_bode_e5f25a_idx'),
        ),
    ]
