# Generated by Django 4.2 on 2026-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productomaquillaje',
            index=models.Index(fields=['nombre'], name='inventario__nombre_398267_idx'),
        ),
        migrations.AddIndex(
            model_name='productomaquillaje',
            index=models.Index(fields=['marca'], name='inventario__marca_5d9590_idx'),
        ),
        migrations.AddIndex(
            model_name='productomaquillaje',
            index=models.Index(fields=['descripcion'], name='inventario__descrip_63c1ff_idx'),
        ),
    ]
