# Generated by Django 4.2 on 2026-06-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VWAgendamientosDiarios',
            fields=[
                ('fecha_agendamiento', models.DateField(primary_key=True, serialize=False)),
                ('total_agendamientos', models.BigIntegerField()),
                ('completados', models.BigIntegerField()),
                ('cancelados', models.BigIntegerField()),
                ('no_asistieron', models.BigIntegerField()),
                ('duracion_promedio_minutos', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Agendamiento Diario (BI)',
                'verbose_name_plural': 'Agendamientos Diarios (BI)',
                'db_table': 'vw_agendamientos_diarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWProductosTopMensual',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('periodo_ym', models.CharField(max_length=7)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('unidades_vendidas', models.BigIntegerField()),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Producto Top Mensual (BI)',
                'verbose_name_plural': 'Productos Top Mensual (BI)',
                'db_table': 'vw_productos_top_mensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWSaludInventario',
            fields=[
                ('id_variante', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_bodega', models.BigIntegerField()),
                ('codigo_bodega', models.CharField(max_length=64)),
                ('nombre_bodega', models.CharField(max_length=255)),
                ('id_producto', models.BigIntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=128)),
                ('cantidad_existencia', models.IntegerField()),
                ('cantidad_reservada', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('nivel_reorden', models.IntegerField(null=True)),
                ('alerta_reorden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Salud de Inventario (BI)',
                'verbose_name_plural': 'Salud de Inventario (BI)',
                'db_table': 'vw_salud_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWValorCliente',
            fields=[
                ('id_usuario_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=512)),
                ('total_pedidos', models.BigIntegerField()),
                ('valor_vida', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_promedio_pedido', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ultimo_pedido_en', models.DateTimeField(null=True)),
                ('puntos_actuales', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Valor de Cliente (BI)',
                'verbose_name_plural': 'Valor de Clientes (BI)',
                'db_table': 'vw_valor_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWVentasDiarias',
            fields=[
                ('fecha_venta', models.DateField(primary_key=True, serialize=False)),
                ('cantidad_pedidos', models.BigIntegerField()),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ticket_promedio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('puntos_generados', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Venta Diaria (BI)',
                'verbose_name_plural': 'Ventas Diarias (BI)',
                'db_table': 'vw_ventas_diarias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=120)),
                ('object_id', models.CharField(blank=True, default='', max_length=120)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
