# Generated by Django 4.2 on 2026-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VWAgendamientosDiarios',
            fields=[
                ('fecha_agendamiento', models.DateField(primary_key=True, serialize=False)),
                ('total_agendamientos', models.BigIntegerField()),
                ('completados', models.BigIntegerField()),
                ('cancelados', models.BigIntegerField()),
                ('no_asistieron', models.BigIntegerField()),
                ('duracion_promedio_minutos', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Agendamiento Diario (BI)',
                'verbose_name_plural': 'Agendamientos Diarios (BI)',
                'db_table': 'vw_agendamientos_diarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWProductosTopMensual',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('periodo_ym', models.CharField(max_length=7)),
                ('nombre_producto', models.CharField(max_length=255)),
                ('unidades_vendidas', models.BigIntegerField()),
                ('ingresos', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'verbose_name': 'Producto Top Mensual (BI)',
                'verbose_name_plural': 'Productos Top Mensual (BI)',
                'db_table': 'vw_productos_top_mensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWSaludInventario',
            fields=[
                ('id_variante', models.BigIntegerField(primary_key=True, serialize=False)),
                ('id_bodega', models.BigIntegerField()),
                ('codigo_bodega', models.CharField(max_length=64)),
                ('nombre_bodega', models.CharField(max_length=255)),
                ('id_producto', models.BigIntegerField()),
                ('nombre_producto', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=128)),
                ('cantidad_existencia', models.IntegerField()),
                ('cantidad_reservada', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('nivel_reorden', models.IntegerField(null=True)),
                ('alerta_reorden', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Salud de Inventario (BI)',
                'verbose_name_plural': 'Salud de Inventario (BI)',
                'db_table': 'vw_salud_inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWValorCliente',
            fields=[
                ('id_usuario_cliente', models.BigIntegerField(primary_key=True, serialize=False)),
                ('correo', models.CharField(max_length=255)),
                ('nombre_cliente', models.CharField(max_length=512)),
                ('total_pedidos', models.BigIntegerField()),
                ('valor_vida', models.DecimalField(decimal_places=2, max_digits=14)),
                ('valor_promedio_pedido', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ultimo_pedido_en', models.DateTimeField(null=True)),
                ('puntos_actuales', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Valor de Cliente (BI)',
                'verbose_name_plural': 'Valor de Clientes (BI)',
                'db_table': 'vw_valor_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VWVentasDiarias',
            fields=[
                ('fecha_venta', models.DateField(primary_key=True, serialize=False)),
                ('cantidad_pedidos', models.BigIntegerField()),
                ('ingresos_brutos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ticket_promedio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('puntos_generados', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Venta Diaria (BI)',
                'verbose_name_plural': 'Ventas Diarias (BI)',
                'db_table': 'vw_ventas_diarias',
                'managed': False,
            },
        ),
    ]
