# Generated by Django 6.0.3 on 2026-03-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
            ],
        ),
    ]
