# Generated by Django 4.2 on 2026-06-17 15:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompra',
            fields=[
                ('id_carrito', models.BigAutoField(db_column='id_carrito', primary_key=True, serialize=False)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('id_cliente_activo', models.BigIntegerField(db_column='id_cliente_activo', editable=False, null=True)),
                ('codigo_moneda', models.CharField(default='COP', max_length=3)),
                ('expira_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='carritos', to='clientes.cliente')),
            ],
            options={
                'db_table': 'carrito_compra',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PedidoVenta',
            fields=[
                ('id_pedido', models.BigAutoField(db_column='id_pedido', primary_key=True, serialize=False)),
                ('numero_pedido', models.CharField(blank=True, default='', max_length=30)),
                ('estado', models.CharField(default='PENDIENTE_PAGO', max_length=25)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_envio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_impuesto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('puntos_ganados', models.PositiveIntegerField(default=0)),
                ('puntos_redimidos', models.PositiveIntegerField(default=0)),
                ('realizado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('carrito', models.ForeignKey(blank=True, db_column='id_carrito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='pedidos.carritocompra')),
                ('cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.RESTRICT, related_name='pedidos', to='clientes.cliente')),
                ('direccion_envio', models.ForeignKey(blank=True, db_column='id_direccion_envio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_envio', to='clientes.direccionusuario')),
                ('direccion_factura', models.ForeignKey(blank=True, db_column='id_direccion_factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_factura', to='clientes.direccionusuario')),
            ],
            options={
                'db_table': 'pedido_venta',
                'ordering': ['-realizado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransaccionPago',
            fields=[
                ('id_transaccion', models.BigAutoField(db_column='id_transaccion', primary_key=True, serialize=False)),
                ('id_transaccion_proveedor', models.CharField(blank=True, max_length=120, null=True)),
                ('estado', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_moneda', models.CharField(default='COP', max_length=3)),
                ('motivo_falla', models.CharField(blank=True, max_length=255, null=True)),
                ('respuesta_cruda_json', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('metodo_pago', models.ForeignKey(blank=True, db_column='id_metodo_pago', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='clientes.metodopagocliente')),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='pedidos.pedidoventa')),
                ('proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones', to='clientes.proveedorpago')),
            ],
            options={
                'db_table': 'transaccion_pago',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ItemCarritoCompra',
            fields=[
                ('id_item_carrito', models.BigAutoField(db_column='id_item_carrito', primary_key=True, serialize=False)),
                ('amount', models.PositiveIntegerField(default=1)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.carritocompra')),
                ('variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.RESTRICT, related_name='items_carrito', to='productos.varianteproducto')),
            ],
            options={
                'db_table': 'item_carrito_compra',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoPedido',
            fields=[
                ('id_historial_estado_pedido', models.BigAutoField(db_column='id_historial_estado_pedido', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=25)),
                ('nota', models.CharField(blank=True, max_length=255, null=True)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, db_column='cambiado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_pedido', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='pedidos.pedidoventa')),
            ],
            options={
                'db_table': 'historial_estado_pedido',
                'ordering': ['-cambiado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetallePedidoVenta',
            fields=[
                ('id_detalle_pedido', models.BigAutoField(db_column='id_detalle_pedido', primary_key=True, serialize=False)),
                ('nombre_producto_snapshot', models.CharField(max_length=180)),
                ('sku_snapshot', models.CharField(max_length=80)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, editable=False, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(db_column='id_pedido', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.pedidoventa')),
                ('variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.RESTRICT, related_name='detalles_pedido', to='productos.varianteproducto')),
            ],
            options={
                'db_table': 'detalle_pedido_venta',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['cliente', 'realizado_en'], name='pedido_vent_id_usua_ed5a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['estado'], name='pedido_vent_estado_8bb2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['numero_pedido'], name='pedido_vent_numero__6fd88a_idx'),
        ),
    ]
