# Generated by Django 4.2 on 2026-06-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccionpago',
            name='metodo_pago_tipo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Tipo de pago'),
        ),
    ]
