# Generated by Django 4.2 on 2026-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['cliente', 'realizado_en'], name='pedido_vent_id_usua_ed5a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['estado'], name='pedido_vent_estado_8bb2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoventa',
            index=models.Index(fields=['numero_pedido'], name='pedido_vent_numero__6fd88a_idx'),
        ),
    ]
