# Generated by Django 6.0.3 on 2026-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=100)),
                ('producto', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
