# Generated by Django 4.2 on 2026-06-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedidoventa_pedido_vent_id_usua_ed5a3c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarritocompra',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
