# Generated by Django 4.2 on 2026-03-31 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedidos_delete_productos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
