# Generated by Django 4.2 on 2026-04-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_create_pedido_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
