# Generated by Django 4.2 on 2026-04-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_pedidos_is_active'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pedidos',
            index=models.Index(fields=['usuario'], name='pedidos_ped_usuario_a1f6fc_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidos',
            index=models.Index(fields=['producto'], name='pedidos_ped_product_1cc2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidos',
            index=models.Index(fields=['direccion'], name='pedidos_ped_direcci_5ad898_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidos',
            index=models.Index(fields=['fecha'], name='pedidos_ped_fecha_375c14_idx'),
        ),
    ]
