# Generated by Django 4.2 on 2026-04-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_remove_clientes_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
