# Generated by Django 4.2 on 2026-06-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id_agendamiento', models.BigAutoField(db_column='id_agendamiento', primary_key=True, serialize=False)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('inicia_en', models.DateTimeField()),
                ('termina_en', models.DateTimeField()),
                ('canal', models.CharField(default='WEB', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.RESTRICT, related_name='agendamientos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamientos_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(db_column='id_usuario_empleado', on_delete=django.db.models.deletion.RESTRICT, related_name='agendamientos', to='usuarios.empleado')),
            ],
            options={
                'db_table': 'agendamiento',
                'ordering': ['-inicia_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaServicio',
            fields=[
                ('id_categoria_servicio', models.BigAutoField(db_column='id_categoria_servicio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'categoria_servicio',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id_tipo_servicio', models.BigAutoField(db_column='id_tipo_servicio', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_servicio',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.BigAutoField(db_column='id_servicio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=140)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveIntegerField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria_servicio', models.ForeignKey(db_column='id_categoria_servicio', on_delete=django.db.models.deletion.RESTRICT, related_name='servicios', to='servicios.categoriaservicio')),
                ('tipo_servicio', models.ForeignKey(db_column='id_tipo_servicio', on_delete=django.db.models.deletion.RESTRICT, related_name='servicios', to='servicios.tiposervicio')),
            ],
            options={
                'db_table': 'servicio',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HistorialEstadoAgendamiento',
            fields=[
                ('id_historial_estado_agendamiento', models.BigAutoField(db_column='id_historial_estado_agendamiento', primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
                ('nota', models.CharField(blank=True, max_length=255, null=True)),
                ('cambiado_en', models.DateTimeField(auto_now_add=True)),
                ('agendamiento', models.ForeignKey(db_column='id_agendamiento', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='servicios.agendamiento')),
                ('cambiado_por', models.ForeignKey(blank=True, db_column='cambiado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_estado_agendamiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'historial_estado_agendamiento',
                'ordering': ['-cambiado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmpleadoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion_personalizada_minutos', models.PositiveIntegerField(blank=True, null=True)),
                ('precio_personalizado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empleado', models.ForeignKey(db_column='id_usuario_empleado', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_asignados', to='usuarios.empleado')),
                ('servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to='servicios.servicio')),
            ],
            options={
                'db_table': 'empleado_servicio',
                'ordering': ['servicio'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='servicio',
            field=models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.RESTRICT, related_name='agendamientos', to='servicios.servicio'),
        ),
    ]
