# Generated by Django 4.2 on 2026-03-26 05:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tipo', models.CharField(choices=[('Manicura', 'Manicura'), ('Pedicura', 'Pedicura'), ('Maquillaje', 'Maquillaje'), ('Tratamiento Facial', 'Tratamiento Facial'), ('Depilación', 'Depilación')], max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Servicio',
                'verbose_name_plural': 'Tipos de Servicio',
                'ordering': ['nombre_tipo'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_servicio', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_servicio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('duracion_servicio', models.CharField(help_text='Ej: 30m, 1h, 1.5h', max_length=255)),
                ('duracion_estimada', models.IntegerField(blank=True, help_text='Duración en minutos', null=True)),
                ('categoria_servicio', models.CharField(max_length=255)),
                ('estado_servicio', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Descontinuado', 'Descontinuado')], default='Activo', max_length=255)),
                ('tipo_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.tiposervicio')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre_servicio'],
            },
        ),
        migrations.CreateModel(
            name='Agendamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_agendamiento', models.DateField()),
                ('hora_agendamiento', models.TimeField()),
                ('estado_agendamiento', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado'), ('No presentado', 'No presentado')], default='Pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamientos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Agendamiento',
                'verbose_name_plural': 'Agendamientos',
                'ordering': ['-fecha_agendamiento', 'hora_agendamiento'],
            },
        ),
    ]
