# Generated by Django 4.2 on 2026-06-16 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleadoservicio',
            options={'managed': True, 'ordering': ['servicio']},
        ),
    ]
