# Generated by Django 4.2 on 2026-03-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamiento',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamientos', to='usuarios.empleado'),
        ),
        migrations.AddField(
            model_name='agendamiento',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamientos', to='servicios.servicio'),
        ),
        migrations.AlterUniqueTogether(
            name='agendamiento',
            unique_together={('fecha_agendamiento', 'hora_agendamiento', 'empleado')},
        ),
    ]
