# Generated by Django 4.2 on 2026-06-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('correo', models.EmailField(db_column='correo', max_length=180, unique=True)),
                ('password', models.CharField(db_column='hash_contrasena', max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.CharField(db_index=True, default='ACTIVO', max_length=20)),
                ('is_staff', models.BooleanField(db_column='es_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='es_superusuario', default=False)),
                ('is_active', models.BooleanField(db_column='es_activo', default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_login', null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'db_table': 'usuario',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PermisoAcceso',
            fields=[
                ('id_permiso', models.BigAutoField(db_column='id_permiso', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('modulo', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'permiso_acceso',
                'ordering': ['modulo', 'accion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RolAcceso',
            fields=[
                ('id_rol', models.BigAutoField(db_column='id_rol', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_sistema', models.BooleanField(db_column='es_sistema', default=False)),
            ],
            options={
                'db_table': 'rol_acceso',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='empleado', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigo_empleado', models.CharField(max_length=40, unique=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('cargo', models.CharField(blank=True, max_length=80, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'db_table': 'perfil_empleado',
                'ordering': ['usuario'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id_codigo', models.BigAutoField(db_column='id_codigo', primary_key=True, serialize=False)),
                ('correo', models.EmailField(db_column='correo_objetivo', db_index=True, max_length=180)),
                ('codigo', models.CharField(db_index=True, max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('expira_en', models.DateTimeField(db_column='expira_en')),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codigo_recuperacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id_usuario_rol', models.BigAutoField(db_column='id_usuario_rol', primary_key=True, serialize=False)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_rol', to='usuarios.rolacceso')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='roles_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuario_rol',
                'managed': True,
                'unique_together': {('id_usuario', 'id_rol')},
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id_rol_permiso', models.BigAutoField(db_column='id_rol_permiso', primary_key=True, serialize=False)),
                ('id_permiso', models.ForeignKey(db_column='id_permiso', on_delete=django.db.models.deletion.CASCADE, related_name='roles_con_permiso', to='usuarios.permisoacceso')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_asignados', to='usuarios.rolacceso')),
            ],
            options={
                'db_table': 'rol_permiso',
                'managed': True,
                'unique_together': {('id_rol', 'id_permiso')},
            },
        ),
        migrations.AddIndex(
            model_name='codigorecuperacion',
            index=models.Index(fields=['correo', 'codigo'], name='codigo_recu_correo__a9cd03_idx'),
        ),
    ]
