# Generated by Django 4.2 on 2026-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(db_index=True, default='ACTIVO', max_length=20),
        ),
    ]
