# Generated by Django 4.2 on 2026-06-17 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoRecuperacion',
            fields=[
                ('id_codigo', models.BigAutoField(db_column='id_codigo', primary_key=True, serialize=False)),
                ('correo', models.EmailField(db_column='correo_objetivo', db_index=True, max_length=180)),
                ('codigo', models.CharField(db_index=True, max_length=6)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_column='creado_en')),
                ('expira_en', models.DateTimeField(db_column='expira_en')),
                ('usado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='codigos_recuperacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codigo_recuperacion',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='codigorecuperacion',
            index=models.Index(fields=['correo', 'codigo'], name='codigo_recu_correo__a9cd03_idx'),
        ),
    ]
