# Generated by Django 4.2 on 2026-06-17 15:35

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtributoDefinicion',
            fields=[
                ('id_atributo', models.BigAutoField(db_column='id_atributo', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('tipo_dato', models.CharField(max_length=20)),
                ('etiqueta_unidad', models.CharField(blank=True, max_length=30, null=True)),
                ('es_filtrable', models.BooleanField(default=True)),
                ('es_eje_variante', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'atributo_definicion',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategoriaCatalogo',
            fields=[
                ('id_categoria', models.BigAutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categoria_catalogo',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarcaCatalogo',
            fields=[
                ('id_marca', models.BigAutoField(db_column='id_marca', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'marca_catalogo',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OpcionAtributo',
            fields=[
                ('id_opcion', models.BigAutoField(db_column='id_opcion', primary_key=True, serialize=False)),
                ('codigo_opcion', models.CharField(max_length=80)),
                ('etiqueta_opcion', models.CharField(max_length=120)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('atributo', models.ForeignKey(db_column='id_atributo', on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='productos.atributodefinicion')),
            ],
            options={
                'db_table': 'opcion_atributo',
                'ordering': ['orden', 'id_opcion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigAutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=160)),
                ('slug', models.CharField(max_length=180, unique=True)),
                ('descripcion_corta', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('descripcion_tecnica', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(db_index=True, default='ACTIVO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, db_column='id_marca', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.marcacatalogo')),
            ],
            options={
                'db_table': 'producto',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id_variante', models.BigAutoField(db_column='id_variante', primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('nombre_variante', models.CharField(blank=True, max_length=140, null=True)),
                ('precio', models.DecimalField(db_index=True, decimal_places=2, max_digits=12)),
                ('costo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('codigo_moneda', models.CharField(default='COP', max_length=3)),
                ('peso_gramos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto')),
            ],
            options={
                'db_table': 'variante_producto',
                'ordering': ['sku'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ValorAtributoVariante',
            fields=[
                ('id_valor_atributo_variante', models.BigAutoField(db_column='id_valor_atributo_variante', primary_key=True, serialize=False)),
                ('valor_texto', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valor_booleano', models.BooleanField(null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_json', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('atributo', models.ForeignKey(db_column='id_atributo', on_delete=django.db.models.deletion.RESTRICT, related_name='valores_variante', to='productos.atributodefinicion')),
                ('opcion', models.ForeignKey(blank=True, db_column='id_opcion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_variante', to='productos.opcionatributo')),
                ('variante', models.ForeignKey(db_column='id_variante', on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributo', to='productos.varianteproducto')),
            ],
            options={
                'db_table': 'valor_atributo_variante',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ValorAtributoProducto',
            fields=[
                ('id_valor_atributo_producto', models.BigAutoField(db_column='id_valor_atributo_producto', primary_key=True, serialize=False)),
                ('valor_texto', models.TextField(blank=True, null=True)),
                ('valor_numero', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('valor_booleano', models.BooleanField(null=True)),
                ('valor_fecha', models.DateField(blank=True, null=True)),
                ('valor_json', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('atributo', models.ForeignKey(db_column='id_atributo', on_delete=django.db.models.deletion.RESTRICT, related_name='valores_producto', to='productos.atributodefinicion')),
                ('opcion', models.ForeignKey(blank=True, db_column='id_opcion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_producto', to='productos.opcionatributo')),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='valores_atributo', to='productos.producto')),
            ],
            options={
                'db_table': 'valor_atributo_producto',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaCatalogo',
            fields=[
                ('id_subcategoria', models.BigAutoField(db_column='id_subcategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_index=True, max_length=100)),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.RESTRICT, related_name='subcategorias', to='productos.categoriacatalogo')),
            ],
            options={
                'db_table': 'subcategoria_catalogo',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReglaAtributoSubcategoria',
            fields=[
                ('id_regla', models.BigAutoField(db_column='id_regla', primary_key=True, serialize=False)),
                ('es_requerido', models.BooleanField(default=False)),
                ('es_filtrable', models.BooleanField(default=True)),
                ('es_eje_variante', models.BooleanField(default=False)),
                ('aplica_a_variantes', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('atributo', models.ForeignKey(db_column='id_atributo', on_delete=django.db.models.deletion.CASCADE, related_name='reglas_subcategoria', to='productos.atributodefinicion')),
                ('subcategoria', models.ForeignKey(db_column='id_subcategoria', on_delete=django.db.models.deletion.CASCADE, related_name='reglas_atributo', to='productos.subcategoriacatalogo')),
            ],
            options={
                'db_table': 'regla_atributo_subcategoria',
                'ordering': ['orden', 'id_regla'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='subcategoria',
            field=models.ForeignKey(db_column='id_subcategoria', on_delete=django.db.models.deletion.RESTRICT, related_name='productos', to='productos.subcategoriacatalogo'),
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id_imagen', models.BigAutoField(db_column='id_imagen', primary_key=True, serialize=False)),
                ('ruta_almacenamiento', models.CharField(max_length=255)),
                ('texto_alternativo', models.CharField(blank=True, max_length=180, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('es_principal', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto')),
                ('variante', models.ForeignKey(blank=True, db_column='id_variante', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagenes', to='productos.varianteproducto')),
            ],
            options={
                'db_table': 'imagen_producto',
                'ordering': ['orden', 'id_imagen'],
                'managed': True,
            },
        ),
    ]
