# Generated by Django 5.2.12 on 2026-03-26 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre_categoria'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(help_text='Descripcion minima de 10 caracteres', validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
