# Generated by Django 4.2 on 2026-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(db_index=True, default='ACTIVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(db_index=True, max_length=160),
        ),
        migrations.AlterField(
            model_name='subcategoriacatalogo',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='precio',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=12),
        ),
    ]
