# Generated by Django 4.2 on 2026-06-17 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='perfil_cliente', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('acepta_fidelizacion', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'perfil_cliente',
                'ordering': ['usuario__correo'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionFidelizacion',
            fields=[
                ('id_config', models.PositiveSmallIntegerField(db_column='id_config', primary_key=True, serialize=False)),
                ('monto_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('puntos_por_unidad', models.PositiveIntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'db_table': 'configuracion_fidelizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProveedorPago',
            fields=[
                ('id_proveedor', models.BigAutoField(db_column='id_proveedor', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'proveedor_pago',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoMetodoPago',
            fields=[
                ('id_tipo_metodo', models.BigAutoField(db_column='id_tipo_metodo', primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_metodo_pago',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuentaFidelizacion',
            fields=[
                ('cliente', models.OneToOneField(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cuenta_fidelizacion', serialize=False, to='clientes.cliente')),
                ('puntos_actuales', models.IntegerField(default=0)),
                ('total_ganados', models.PositiveIntegerField(default=0)),
                ('total_redimidos', models.PositiveIntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
            ],
            options={
                'db_table': 'cuenta_fidelizacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MetodoPagoCliente',
            fields=[
                ('id_metodo_pago', models.BigAutoField(db_column='id_metodo_pago', primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('etiqueta_mascara', models.CharField(max_length=80)),
                ('nombre_titular', models.CharField(blank=True, max_length=120, null=True)),
                ('ultimos4', models.CharField(blank=True, max_length=4, null=True)),
                ('mes_expiracion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anio_expiracion', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('REVOCADO', 'Revocado')], default='ACTIVO', max_length=20)),
                ('id_propietario_predeterminado', models.BigIntegerField(db_column='id_propietario_predeterminado', editable=False, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='clientes.cliente')),
                ('proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodos_cliente', to='clientes.proveedorpago')),
                ('tipo_metodo', models.ForeignKey(db_column='id_tipo_metodo', on_delete=django.db.models.deletion.RESTRICT, related_name='metodos_cliente', to='clientes.tipometodopago')),
            ],
            options={
                'db_table': 'metodo_pago_cliente',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LibroPuntos',
            fields=[
                ('id_movimiento_puntos', models.BigAutoField(db_column='id_movimiento_puntos', primary_key=True, serialize=False)),
                ('pedido_id', models.BigIntegerField(blank=True, db_column='id_pedido', null=True)),
                ('tipo_origen', models.CharField(choices=[('ORDEN_GANA', 'Orden gana puntos'), ('ORDEN_REDIME', 'Orden redime puntos'), ('AJUSTE_MANUAL', 'Ajuste manual'), ('EXPIRACION', 'Expiración')], max_length=20)),
                ('puntos_delta', models.IntegerField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='id_usuario_cliente', on_delete=django.db.models.deletion.RESTRICT, related_name='movimientos_puntos', to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, db_column='creado_por', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'libro_puntos',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DireccionUsuario',
            fields=[
                ('id_direccion', models.BigAutoField(db_column='id_direccion', primary_key=True, serialize=False)),
                ('tipo_direccion', models.CharField(choices=[('ENVIO', 'Envío'), ('FACTURA', 'Factura'), ('OTRA', 'Otra')], max_length=20)),
                ('etiqueta', models.CharField(blank=True, max_length=60, null=True)),
                ('nombre_destinatario', models.CharField(max_length=120)),
                ('linea1', models.CharField(max_length=160)),
                ('linea2', models.CharField(blank=True, max_length=160, null=True)),
                ('ciudad', models.CharField(max_length=80)),
                ('departamento', models.CharField(blank=True, max_length=80, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('codigo_pais', models.CharField(default='CO', max_length=2)),
                ('es_predeterminada_envio', models.BooleanField(default=False)),
                ('es_predeterminada_factura', models.BooleanField(default=False)),
                ('id_usuario_envio_predeterminado', models.BigIntegerField(db_column='id_usuario_envio_predeterminado', editable=False, null=True)),
                ('id_usuario_factura_predeterminado', models.BigIntegerField(db_column='id_usuario_factura_predeterminado', editable=False, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True, db_column='actualizado_en')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'direccion_usuario',
                'ordering': ['-creado_en'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='direccionusuario',
            index=models.Index(fields=['usuario', 'es_predeterminada_envio'], name='direccion_u_id_usua_ab1893_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionusuario',
            index=models.Index(fields=['usuario', 'es_predeterminada_factura'], name='direccion_u_id_usua_3b9cde_idx'),
        ),
    ]
