# Generated by Django 4.2 on 2026-03-26 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('puntos_fidelidad', models.IntegerField(default=0, help_text='Puntos de fidelidad acumulados')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['usuario__nombre1'],
            },
        ),
        migrations.CreateModel(
            name='ServicioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_comunicacion', models.CharField(choices=[('WhatsApp', 'WhatsApp'), ('Email', 'Email'), ('Teléfono', 'Teléfono'), ('Presencial', 'Presencial')], max_length=50)),
                ('control_agendamiento', models.CharField(choices=[('Agendado', 'Agendado'), ('Pendiente', 'Pendiente'), ('Completado', 'Completado')], default='Pendiente', max_length=20)),
                ('cupones', models.IntegerField(default=0)),
                ('estado_ticket', models.CharField(choices=[('Abierto', 'Abierto'), ('Cerrado', 'Cerrado'), ('En espera', 'En espera')], default='Abierto', max_length=20)),
                ('fecha_contacto', models.DateField(auto_now_add=True)),
                ('promociones', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_cliente', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Servicio al Cliente',
                'verbose_name_plural': 'Servicios al Cliente',
                'ordering': ['-fecha_contacto'],
            },
        ),
    ]
