# Generated by Django 4.2 on 2026-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direccionusuario',
            name='tipo_direccion',
            field=models.CharField(choices=[('ENVIO', 'Envío'), ('FACTURA', 'Factura'), ('OTRA', 'Otra')], max_length=20),
        ),
        migrations.AlterField(
            model_name='libropuntos',
            name='tipo_origen',
            field=models.CharField(choices=[('ORDEN_GANA', 'Orden gana puntos'), ('ORDEN_REDIME', 'Orden redime puntos'), ('AJUSTE_MANUAL', 'Ajuste manual'), ('EXPIRACION', 'Expiración')], max_length=20),
        ),
        migrations.AlterField(
            model_name='metodopagocliente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('REVOCADO', 'Revocado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddIndex(
            model_name='direccionusuario',
            index=models.Index(fields=['usuario', 'es_predeterminada_envio'], name='direccion_u_id_usua_ab1893_idx'),
        ),
        migrations.AddIndex(
            model_name='direccionusuario',
            index=models.Index(fields=['usuario', 'es_predeterminada_factura'], name='direccion_u_id_usua_3b9cde_idx'),
        ),
    ]
