# Generated by Django 5.2.12 on 2026-03-26 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='puntos_fidelidad',
            field=models.IntegerField(default=0, help_text='Puntos de fidelidad acumulados', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='serviciocliente',
            name='cupones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='serviciocliente',
            name='promociones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
