"""
Django settings for Profesional Beauty project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
import sys
import logging
from logging.handlers import RotatingFileHandler
from django.core.exceptions import ImproperlyConfigured
from urllib.parse import urlparse
import dj_database_url

DB_ENGINE = os.environ.get('DB_ENGINE', 'sqlite').strip().lower()
if DB_ENGINE in {'mysql', 'mariadb'}:
    import pymysql
    pymysql.install_as_MySQLdb()
    # Bypass para versiones antiguas de MariaDB (10.4)
    from django.db.backends.base.base import BaseDatabaseWrapper
    BaseDatabaseWrapper.check_database_version_supported = lambda self: None

# Database configuration is handled later using dj-database-url and DATABASE_URL

# Patch para compatibilidad de Django 4.2 con Python 3.14+ (Template Context)
from django.template import context
def patch_context_copy(self):
    import copy
    new_copy = self.__class__.__new__(self.__class__)
    new_copy.__dict__.update(self.__dict__)
    new_copy.dicts = self.dicts[:]
    return new_copy
context.BaseContext.__copy__ = patch_context_copy

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(exist_ok=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

def get_env_bool(name: str, default: bool = False):
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.strip().lower() in {'1', 'true', 'yes', 'on'}


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_bool('DJANGO_DEBUG', True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-local-dev-only-change-me'
    else:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY is required when DJANGO_DEBUG is false.')

def get_env_list(name: str, default: str = ""):
    raw = os.environ.get(name, default)
    parts = [p.strip() for p in raw.replace(';', ',').split(',')]
    return [p for p in parts if p]

ALLOWED_HOSTS = get_env_list('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost,testserver')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cloudinary_storage',
    'cloudinary',
    'rest_framework',
    'core',
    'productos',
    'pedidos',
    'clientes',
    'servicios',
    'inventario',
    'web',
    'django_extensions',
    'usuarios',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.AnonymousRouteGuardMiddleware',
    'core.middleware.NoStoreAuthenticatedPagesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'nailsnice.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nailsnice.wsgi.application'


# DATABASES will be configured below using dj-database-url after DEBUG is set.

# DATABASES for test run are configured dynamically below.


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True
USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
# Permite servir el directorio `/static/` del proyecto (p.ej. `static/css/style.css`)
# sin necesidad de meter assets dentro de cada app.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles_build'
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Cloudinary Storage Configuration
# Si CLOUDINARY_URL está configurado, usamos la nube. Si no, fallback a local.
if os.environ.get('CLOUDINARY_URL'):
    import cloudinary
    import dj_database_url
    # CLOUDINARY_URL format: cloudinary://API_KEY:API_SECRET@CLOUD_NAME
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': os.environ.get('CLOUDINARY_URL').split('@')[1] if '@' in os.environ.get('CLOUDINARY_URL') else '',
        'API_KEY': os.environ.get('CLOUDINARY_URL').split('://')[1].split(':')[0] if '://' in os.environ.get('CLOUDINARY_URL') else '',
        'API_SECRET': os.environ.get('CLOUDINARY_URL').split(':')[2].split('@')[0] if '@' in os.environ.get('CLOUDINARY_URL') else '',
    }
    # django-cloudinary-storage automatically parses CLOUDINARY_URL globally for cloudinary python library too
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Cookies y seguridad en producción
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_SECURE = True
CSRF_COOKIE_HTTPONLY = True
SECURE_SSL_REDIRECT = (os.environ.get('SECURE_SSL_REDIRECT', 'false').lower() in {'1', 'true', 'yes'})

# Solo habilitar HSTS cuando realmente se fuerza HTTPS; si no, evitar que el navegador recuerde https
SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000')) if SECURE_SSL_REDIRECT else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = SECURE_SSL_REDIRECT
SECURE_HSTS_PRELOAD = SECURE_SSL_REDIRECT and (os.environ.get('SECURE_HSTS_PRELOAD', 'false').lower() in {'1', 'true', 'yes'})

SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', '7200'))
SESSION_SAVE_EVERY_REQUEST = True

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'

# En desarrollo desactiva HTTPS forzado y cookies seguras para evitar redirecciones a https://127.0.0.1:8000
if DEBUG:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_SSL_REDIRECT = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configure DATABASES from DATABASE_URL using dj-database-url (Render internal DB recommended)
# Use the Render internal URL as a sensible default if DATABASE_URL is not set.
DATABASE_URL = os.environ.get('DATABASE_URL', 'postgresql://admin:2O4M5jI0KvBVpo6fkwZd9l8S8bpQ0JgB@dpg-d8pg2s5ckfvc73a89g4g-a/Profesional Beauty')

# Parche maestro: Render no resuelve los hosts internos (dpg-...) durante la fase de Build.
# Si falla la resolucion DNS, forzamos SQLite temporalmente para que manage.py no falle.
import socket
from urllib.parse import urlparse
if DATABASE_URL.startswith('postgres'):
    try:
        db_host = urlparse(DATABASE_URL).hostname
        if db_host:
            socket.gethostbyname(db_host)
    except Exception:
        DATABASE_URL = 'sqlite:///' + str(BASE_DIR / 'db.sqlite3')

# If DATABASE_URL is a sqlite URL (local dev/migrations), configure SQLite directly
if DATABASE_URL.startswith('sqlite'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600, ssl_require=(os.environ.get('DJANGO_DEBUG','').lower() not in {'1','true','yes'}))
    }

# Use SQLite for tests to avoid external DB dependency during CI/local runs.
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

# Custom User Model
AUTH_USER_MODEL = 'usuarios.Usuario'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# CORS Configuration
CORS_ALLOWED_ORIGINS = get_env_list('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://127.0.0.1:3000')
CORS_ALLOW_CREDENTIALS = True

# DRF Configuration
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# Cache (LocMem por defecto; Redis si REDIS_URL esta definido)
REDIS_URL = os.environ.get('REDIS_URL', '').strip()
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {
                'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            },
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'nailsnice-local',
        }
    }

# ---------------------------------------------------------------------------
# Configuración de correo — Alta resiliencia para producción en Render
# ---------------------------------------------------------------------------
# Variables de entorno requeridas en producción:
#   EMAIL_HOST_USER     → cuenta de correo (ej. soporteProfesional Beauty@gmail.com)
#   EMAIL_HOST_PASSWORD → contraseña de app (App Password en Gmail)
#
# Variables opcionales con defaults razonables:
#   EMAIL_HOST      → smtp.gmail.com  (o smtp.hostinger.com, etc.)
#   EMAIL_PORT      → 465 por defecto (SSL directo, nunca capado por Render)
#   EMAIL_USE_SSL   → true  (compatible con port 465)
#   EMAIL_USE_TLS   → false (mutuamente excluyente con SSL)
#
# Si el puerto 465 estuviese bloqueado, cambia EMAIL_PORT=587 y EMAIL_USE_TLS=true
# desde el panel de Render sin necesidad de redeploy.
# ---------------------------------------------------------------------------
if os.environ.get('EMAIL_HOST_USER') and os.environ.get('EMAIL_HOST_PASSWORD'):
    EMAIL_BACKEND    = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST       = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_HOST_USER  = os.environ.get('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')

    # Detección automática del modo SSL vs TLS según las env vars.
    # Por defecto usamos puerto 465 + SSL (más compatible con Render).
    _use_ssl = get_env_bool('EMAIL_USE_SSL', True)
    _use_tls = get_env_bool('EMAIL_USE_TLS', False)

    # Prevenir configuración inválida: SSL y TLS son mutuamente excluyentes.
    if _use_ssl and _use_tls:
        _use_tls = False  # SSL tiene prioridad

    EMAIL_USE_SSL = _use_ssl
    EMAIL_USE_TLS = _use_tls

    # Puerto inteligente: 465 con SSL, 587 con TLS, sobrescribible por env var.
    _default_port = 465 if _use_ssl else 587
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', str(_default_port)))

    # Timeout corto para no bloquear el proceso web si el SMTP no responde.
    EMAIL_TIMEOUT = 8

    DEFAULT_FROM_EMAIL = os.environ.get(
        'DEFAULT_FROM_EMAIL',
        f'Profesional Beauty <{EMAIL_HOST_USER}>'
    )
else:
    # Modo desarrollo / sin credenciales: imprime en consola de runserver.
    EMAIL_BACKEND      = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = os.environ.get(
        'DEFAULT_FROM_EMAIL',
        'Profesional Beauty <soporteProfesional Beauty@gmail.com>'
    )

# Logging básico orientado a producción: guarda errores 400/500 y excepciones en logs/app.log
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{levelname}] {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'app.log',
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
            'encoding': 'utf-8',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
        'nailsnice': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
AUTH_USER_MODEL = 'usuarios.Usuario'

# ---------------------------------------------------------------------------
# Configuración condicional de Cloudinary para almacenamiento persistente
# ---------------------------------------------------------------------------
CLOUDINARY_CLOUD_NAME = os.environ.get('CLOUDINARY_CLOUD_NAME')
CLOUDINARY_API_KEY = os.environ.get('CLOUDINARY_API_KEY')
CLOUDINARY_API_SECRET = os.environ.get('CLOUDINARY_API_SECRET')

if CLOUDINARY_CLOUD_NAME and CLOUDINARY_API_KEY and CLOUDINARY_API_SECRET:
    CLOUDINARY_STORAGE = {
        'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
        'API_KEY': CLOUDINARY_API_KEY,
        'API_SECRET': CLOUDINARY_API_SECRET,
    }
    DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

    if 'cloudinary_storage' not in INSTALLED_APPS:
        INSTALLED_APPS.append('cloudinary_storage')
    if 'cloudinary' not in INSTALLED_APPS:
        INSTALLED_APPS.append('cloudinary')

print(">>> BASE_DIR:", BASE_DIR)
print(">>> STATIC_DIRS:", STATICFILES_DIRS)
